[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "study"
    name = "Study"
    url = "/study"
    weight = 2

[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 3

[[main]]
    identifier = "ideas"
    name = "Ideas"
    url = "/ideas"
    weight = 4
    
# Social Media Configuration


[[social]]
    identifier = "instagram"
    name = "LinkedIn"
    url = "#"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/yoongang02"
    weight = 3